rectangle_region:
  type: rectangle
  x1: 110
  y1: 430
  x2: 250
  y2: 680
  # 这边的(x1,y1),(x2,y2)可以理解为相对bluestack左上角坐标的坐标。
  # 也就是bluestack左上角的顶点是原点时候的相对坐标。

  # 我现在的思路是，进入游戏先把视野最大化，然后好像放兵的那块区域就（相对于bluestacks左上角坐标）不变。

# 可以加更多区域...
